### ISSUE TITLE
Gerber files for adapter board

### ISSUE THREAD

**Issue by ejona86** [pdp11gy/SoC-HPS-based-MFM-disk-emulator#1]
This repo describes the usage and software, but I didn't see any real details about the adapter board. I found http://pdp11gy.com/BV/MFM_Interface_v2.pdf, which is enough to re-create the board, but I was wondering if Gerber files are available to make the fabrication process easier.

**Comment by pdp11gy** [comment]
Hello, send me an E-Mail ( info@pdp11gy.com ) and I will return all the Gerber files for reproducing the board.
